# Generated by Django 4.2.5 on 2024-02-12 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journalist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('biography', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='article',
            old_name='publication',
            new_name='publication_date',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='location',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news.journalist'),
        ),
    ]
